apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
      annotations:
        consul.hashicorp.com/connect-service-upstreams: "postgres:5432"
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: admindb
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
      annotations:
        consul.hashicorp.com/connect-service-upstreams: "pgadmin:8080"
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:2023-08-21-1
          ports:
            - containerPort: 80
              name: pgadmin-port
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pgadmin
# spec:
#   selector:
#     app: pgadmin
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080