apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demoapp-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demoapp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  